Practices/DynastyAppDemo/DynastyApp/Controllers/CustomerController.cs
using DynastyApp.Core.Contract.Service;
using DynastyApp.Core.Model;
using DynastyApp.Infrastructure.Service;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace DynastyApp.WebAPI.Controllers
{
    public class CustomerController : Controller
    {
        private readonly ICustomerServiceAsync _customerServiceAsync;
        private readonly IRegionServiceAsync _regionServiceAsync;

        public CustomerController(ICustomerServiceAsync customerServiceAsync, IRegionServiceAsync regionServiceAsync)
        {
            _customerServiceAsync = customerServiceAsync;
            _regionServiceAsync = regionServiceAsync;
        }

        public async Task<IActionResult> Index()
        {
            var collection = await _customerServiceAsync.GetAllAsync();
            if (collection != null)
                return View(collection);

            List<CustomerResponseModel> model = new List<CustomerResponseModel>();
            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            var collection = await _regionServiceAsync.GetAllAsync();
            ViewBag.Regions = new SelectList(collection, "Id", "Name");

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(CustomerRequestModel model)
        {
            if (ModelState.IsValid)
            {
                await _customerServiceAsync.AddCustomerAsync(model);
                return RedirectToAction("Index");
            }

            var collection = await _regionServiceAsync.GetAllAsync();
            ViewBag.Regions = new SelectList(collection, "Id", "Name");
            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            ViewBag.IsEdit = false;
            var custModel = await _customerServiceAsync.GetCustomerForEditAsync(id);
            var regCollection = await _regionServiceAsync.GetAllAsync();
            ViewBag.Regions = new SelectList(regCollection, "Id", "Name");

            return View(custModel);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(CustomerRequestModel model)
        {
            ViewBag.IsEdit = false;
            var collection = await _regionServiceAsync.GetAllAsync();
            ViewBag.Regions = new SelectList(collection, "Id", "Name");
            if (ModelState.IsValid)
            {
                await _customerServiceAsync.UpdateCustomerAsync(model);
                ViewBag.IsEdit = true;
            }

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            await _customerServiceAsync.DeleteCustomerAsync(id);
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Detail()
        {
            var collection = await _customerServiceAsync.GetAllAsync();
            if (collection != null)
                return View(collection);

            List<CustomerResponseModel> model = new List<CustomerResponseModel>();
            return View(model);
        }

    }

}

Practices/DynastyAppDemo/DynastyApp/Controllers/EmployeeController.cs
using DynastyApp.Core.Contract.Service;
using DynastyApp.Core.Model;
using DynastyApp.Infrastructure.Service;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace DynastyApp.WebMVC.Controllers
{
    public class EmployeeController : Controller
    {
        private readonly IEmployeeServiceAsync _employeeServiceAsync;
        public EmployeeController(IEmployeeServiceAsync employeeServiceAsync)
        {
            _employeeServiceAsync = employeeServiceAsync;
        }

        public async Task<IActionResult> Index()
        {
            var empCollection = await _employeeServiceAsync.GetAllAsync();
            if (empCollection != null)
                return View(empCollection);

            List<EmployeeResponseModel> model = new List<EmployeeResponseModel>();
            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
    
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(EmployeeRequestModel model)
        {
            if (ModelState.IsValid)
            {
                await _employeeServiceAsync.AddEmployeeAsync(model);
                return RedirectToAction("Index");
            }
     
            return View(model);
        }


        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            ViewBag.IsEdit = false;
            var empModel = await _employeeServiceAsync.GetEmployeeForEditAsync(id);
          
            return View(empModel);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(EmployeeRequestModel model)
        {
            ViewBag.IsEdit = false;
        
            if (ModelState.IsValid)
            {
                await _employeeServiceAsync.UpdateEmployeeAsync(model);
                ViewBag.IsEdit = true;

            }

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            await _employeeServiceAsync.DeleteEmployeeAsync(id);
            return RedirectToAction("Index");
        }

        [NonAction]
        public void Demo()
        {
        }


        public async Task<IActionResult> Detail()
        {
            var empCollection = await _employeeServiceAsync.GetAllAsync();
            if (empCollection != null)
                return View(empCollection);

            List<EmployeeResponseModel> model = new List<EmployeeResponseModel>();
            return View(model);
        }
    }
}

Practices/DynastyAppDemo/DynastyApp/Controllers/RegionController.cs
using DynastyApp.Core.Contract.Service;
using DynastyApp.Core.Model;
using DynastyApp.Infrastructure.Service;
using Microsoft.AspNetCore.Mvc;

namespace DynastyApp.WebMVC.Controllers
{
    public class RegionController : Controller
    {
        private readonly IRegionServiceAsync _regionServiceAsync;
        public RegionController(IRegionServiceAsync regionServiceAsync)
        {
            _regionServiceAsync = regionServiceAsync;
        }

        public async Task<IActionResult> Index()
        {
           var result = await _regionServiceAsync.GetAllAsync();
            if( result != null)
                return View(result);

            List<RegionModel> lmodel = new List<RegionModel>();
            return View(lmodel);
            
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(RegionModel regionModel)
        {
            if (ModelState.IsValid)
            {
                await _regionServiceAsync.AddRegionAsync(regionModel);
                return RedirectToAction("Index");
            }
            return View(regionModel);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            ViewBag.IsEdit = false;
            var result = await _regionServiceAsync.GetRegionForEditAsync(id);
            return View(result);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(RegionModel regionModel)
        {
            ViewBag.IsEdit = false;
            if (ModelState.IsValid)
            {
                await _regionServiceAsync.UpdateRegionAsync(regionModel);
                ViewBag.IsEdit = true;
            }
            return View(regionModel);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            await _regionServiceAsync.DeleteRegionAsync(id);
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Detail()
        {
            var collection = await _regionServiceAsync.GetAllAsync();
            if (collection != null)
                return View(collection);

            List<RegionModel> lmodel = new List<RegionModel>();
            return View(lmodel);
        }


    }
}

Practices/DynastyAppDemo/DynastyApp/Views/Shared/_CustomerCard.cshtml
@model CustomerResponseModel

<div class="col mb-3">
    <div class="card" style="width: 18rem;">
        <div class="card-body">
            <h5 class="card-title">@Model.Title @Model.Name</h5>
            <p class="card-text">@Model.Phone</p>
            <p class="card-text">@Model.Address</p>
            <a asp-action="Edit" asp-controller="Customer" asp-route-id="@Model.Id" class="btn btn-primary">Edit</a>
            <a class="btn bg-danger" asp-action="Delete" asp-controller="Customer" asp-route-id="@Model.Id">Delete</a>
            <a class="btn bg-info" asp-action="Detail" asp-controller="Customer" asp-route-id="@Model.Id">Detail</a>
        </div>
    </div>
</div>

Practices/DynastyAppDemo/DynastyApp/Views/Shared/_EmployeeCard.cshtml
@model EmployeeResponseModel

<div class="col mb-3">
    <div class="card" style="width: 18rem;">
        <img src="@Model.PhotoPath" class="card-img-top" alt="...">
        <div class="card-body">
            <h5 class="card-title">@Model.FullName</h5>
            <p class="card-text">@Model.Address</p>
            <a asp-action="Edit" asp-controller="Employee" asp-route-id="@Model.Id" class="btn btn-primary">Edit</a>
            <a class="btn bg-danger" asp-action="Delete" asp-controller="Employee" asp-route-id="@Model.Id">Delete <i class="fa fa-info-circle"></i> </a>
            <a class="btn bg-info" asp-action="Detail" asp-controller="Employee" asp-route-id="@Model.Id">Detail</a>
        </div>
    </div>
</div>

Practices/DynastyAppDemo/DynastyApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DynastyApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/DynastyApp.styles.css" asp-append-version="true" />
</head>
<body>
    <partial name="_header"></partial>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <partial name="_footer"></partial>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Practices/DynastyAppDemo/DynastyApp/Views/Shared/_RegionRow.cshtml
@model RegionModel
<tr>
    <td>@Model.Id</td>
    <td>@Model.Name</td>
    <td>
        <span>
            <a asp-controller="Region" asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-primary">Edit</a>
            <a asp-controller="Region" asp-action="Delete" asp-route-id="@Model.Id" class="btn btn-danger">Delete</a>
        </span>
    </td>
</tr>

Practices/DynastyAppDemo/DynastyApp/Views/Shared/_footer.cshtml
<footer class="border-top footer text-muted" style="position:absolute; left:0px; right:0px;bottom:0px;">
    <div class="container">
        &copy; 2022 - Ken Personal Website - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>

Practices/DynastyAppDemo/DynastyApp/Views/Shared/_header.cshtml
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">DynastyApp.WebMVC</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <div id="nav">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Employee" asp-action="Index">Employee</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Region" asp-action="Index">Region</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Customer" asp-action="Index">Customer</a>
                        </li>
                        

                    </ul>
                </div>
            </div>
        </div>
    </nav>
</header>